---
apiVersion: v1
kind: Namespace
metadata:
  name: redis
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: redis
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9122"
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:5
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 6379
        - name: redis-exporter
          image: filipecosta90/redisearch_exporter:latest
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 9122
