# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build: # test with redisearch:edge
    docker:
      - image: circleci/golang:1.12
      - image: redislabs/redisearch:edge

    working_directory: /go/src/github.com/filipecosta90/redisearch_prometheus_exporter
    steps:
      - checkout
      - run: make coverage
      - run: bash <(curl -s https://raw.githubusercontent.com/codecov/codecov-action/master/codecov) -t ${CODECOV_TOKEN}

  build-latest:
    docker:
      - image: circleci/golang:1.12
      - image: redislabs/redisearch:latest

    working_directory: /go/src/github.com/filipecosta90/redisearch_prometheus_exporter
    steps:
      - checkout
      - run: make test

  build-v16:
    docker:
      - image: circleci/golang:1.12
      - image: redislabs/redisearch:1.6.13

    working_directory: /go/src/github.com/filipecosta90/redisearch_prometheus_exporter
    steps:
      - checkout
      - run: make test

  build-v14:
    docker:
      - image: circleci/golang:1.12
      - image: redislabs/redisearch:1.4.28

    working_directory: /go/src/github.com/filipecosta90/redisearch_prometheus_exporter
    steps:
      - checkout
      - run: make test

  build_nightly: # test nightly with redisearch:edge
    docker:
      - image: circleci/golang:1.12
      - image: redislabs/redisearch:edge

    working_directory: /go/src/github.com/filipecosta90/redisearch-go
    steps:
      - checkout
      - run: make test

workflows:
  version: 2
  commit:
    jobs:
      - build
      - build-latest
      - build-v16
      - build-v14
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build_nightly
      - build-latest
      - build-v16
      - build-v14